### ISSUE TITLE
Nothing works after plugin installation

### ISSUE THREAD

**Issue by refaelsh** [mrshmllow/orgmode-babel.nvim#1]
I installed the plugin using packer like this:
```lua
use 'mrshmllow/orgmode-babel.nvim'
```

No new commands were added. Specifically no `OrgTangle`.

**Comment by mrshmllow** [comment]
You must add `require("orgmode-babel").setup({ opts })`

**Comment by mrshmllow** [comment]
I added an example packer configuration

**Comment by refaelsh** [comment]
> I added an example packer configuration

The example did not work. I needed to change this line:
```lua
langs = { "python", "lua", ... }
```
to this line:
```lua
langs = { "python", "lua", "nix" },
```
I am not really sure why, I am not a big Lua knower.

Thank you :-)
