### ISSUE TITLE
where to find babel packages for lua / bash (eventually nix)

### ISSUE THREAD

**Issue by teto** [mrshmllow/orgmode-babel.nvim#4]
Hi,

Pretty excited by this plugin, sadly I dont know a thing about emacs and I can't execute code for lua or even bash. Where should I look at to install those packages ? (would be nice if you could provide the matching load_paths).
I found a lua-mode here https://melpa.org/#/?q=lua-mode is that helpful ? couldn't find any "babel" reference in that repo or in your dotfiles if that matters.
For more context see
https://discourse.nixos.org/t/use-orgmode-in-neovim-how-to-get-emacs-babel-lua-bash-python-from-nixpkgs/35059

**Comment by mrshmllow** [comment]
Hello. You specify languages you would like this plugin to work with in `opts.langs = { ... }`

You can find a list of languages babel supports bult-in here: https://orgmode.org/worg/org-contrib/babel/languages/index.html

In your case, lua and bash are built-in to orgmode

Here is an example configuration just for you

```lua
use {
  "mrshmllow/orgmode-babel.nvim",
  requires = {
    "nvim-orgmode/orgmode",
    "nvim-treesitter/nvim-treesitter"
  },
  cmd = { "OrgExecute", "OrgTangle" },
  opt = true,
  config = function ()
    require("orgmode-babel").setup({
      langs = { "lua", "shell" },
    })
  end
}
```

In nix, orgmode packages are prefixed with `emacsPackages.ob-` and you can see a list of them here https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=emacsPackages.ob

**After installing a emacsPackages.ob-, you dont have to list them in load_paths**

**Comment by teto** [comment]
Yes that worked, I had some bugs at some point but they disappeared. It could be cool to add some tests that could serve as example (for instance I discovered via your README one could name the blocks, thanks for linking https://orgmode.org/manual/Structure-of-Code-Blocks.html) . I would like to package the plugin in nixpkgs.
